name: Test action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RCSandberg/dart-read-package-semantic-version-action@main
        id: call-action
        with:
          path: assets/with-build.yaml
      - uses: nick-fields/assert-action@v2
        with:
          expected: 1.2.3+4
          actual: ${{ steps.call-action.outputs.package-semantic-version }}
      - uses: nick-fields/assert-action@v2
        with:
          expected: 1.2.3
          actual: ${{ steps.call-action.outputs.package-version }}
      - uses: nick-fields/assert-action@v2
        with:
          expected: 4
          actual: ${{ steps.call-action.outputs.package-build-version }}
      - run: echo "Read semantic version ${{ steps.call-action.outputs.package-semantic-version }}"
      - run: echo "Read version ${{ steps.call-action.outputs.package-version }}"
      - run: echo "Read version ${{ steps.call-action.outputs.package-build-version }}"
